### PR TITLE
Add support for other VCARD dates (e.g. X-ANNIVERSARY)

### LINKED ISSUE #243: Parse out other events similar to 'birthday'
I see `X-ANNIVERSARY` tags at least. There are probably others in use too.

### PR DESCRIPTION
**Pull request by d7415**
Fixes #243

2 problems at the moment (which Travis will report on shortly)

1) The definition line for `update_vcf_dates()` is too long (101 chars). I thought about `update_vcfdates()` or similar, but figured I'd push first and ask later.
2) There's a UNIQUE constraint violation. I can't see how the old function got around it. I'll keep looking, but help is welcome!

Other notes:
* I've changed the function and variable names to be more generic and added a docstring.
* I modified the `href` for the vcard-related events to be `href+vcard_fieldname`. This was because khal as a whole is set up for one event per file, and contacts may have e.g. a birthday and an anniversary. This might have caused (2) above...
* I might have a little time tomorrow, otherwise it will probably be a week or so before I can get back to this. Feel free to carry on in my absence or wait.
* Other feedback (style/approach/etc) welcome.

### CODE REVIEW

**Comment by geier** [comment]
I had a quick look through your changes and I like the approach. Thanks for taking the time to do this! If I find some more time, I'll see if I can help you with that unique problem.

**Comment by d7415** [comment]
Ok. I still don't know why it used to work, but I think it should work now.

The `test_birthdays_update` test passes, the reason it passes makes sense, but I'm still a little concerned that I don't know how I broke it, so I might have missed something.

**Comment by d7415** [comment]
Just to confirm that (now that I've stopped adding commits) I think this is ready for review/merge.

**Comment by d7415** [comment]
> Just to confirm that (now that I've stopped adding commits) I think this is ready for review/merge.

Let's try that again.

**Comment by geier** [comment]
Seems to work fine, thanks for your work!

**Pull request merged**
