### PR TITLE
Add `printics` functionality

### PR DESCRIPTION
**Pull request by dopefishh**
As mentioned in issue #469

### CODE REVIEW

**Comment by hobarrera** [comment]
Hi. Thanks for contributing.

Please rebase to master (to get rid of the merge commits), and squash your two author-related commits. Also, there seems to be a small style violation regarding a missing newline (see the travis output).

**Comment by hobarrera** [comment]
(The rest of the code seems fine to me 👍🏻)

**Comment by dopefishh** [comment]
working on it

**Comment by hobarrera** [comment]
@untitaker I believe this is superceded by #478

**Comment by untitaker** [comment]
Ah ok.

**Pull request closed without merging**
