### PR TITLE
Import (and printics) from stdin if no filename is provided

### LINKED ISSUE #522: import ICS from stdin
Hi,

Wanting to use khal from mutt, I think it should be quite nice to be able to import a .ics file from stdin, for example typing in mutt:

```
| khal import -a personal -
```

This would avoid manually building a unique name for the .ics file.

### PR DESCRIPTION
**Pull request by geier**
supersedes #652, closes #522

### CODE REVIEW

**Comment by hobarrera** [comment]
That `sys.stdin = open('/dev/tty', 'r')` thing is a neat trick, cool! 👌

I pushed a small commit that dedupes some code, I hope you don't mind my pushing into this branch. :)

**Comment by geier** [comment]
Feel free to push to "my" branches, but please leave a note (like you did here) so I don't accidentally force push over it.

**Comment by geier** [comment]
@hobarrera thing is, this doesn't really work as is, because `import` takes several arguments, `printics` only one.

**Comment by hobarrera** [comment]
Whoops! Fixed that, sorry!

**Comment by geier** [comment]
note: I rebased on master.

**Pull request merged**
