### PR TITLE
Tweak sleep_time to be as precise as possible

### PR DESCRIPTION
**Pull request by hobarrera**
Tweak sleep_time to be as precise as possible, and also account for possible rounding error when our sleep is equal to the maximum precision (basically, for rounding in our favour).

See [this discussion](https://github.com/pimutils/khal/pull/575#pullrequestreview-22009618).

### CODE REVIEW

**Comment by untitaker** [comment]
It appears your last value of `1.1` is still not enough. I'd try starting with `0.001` and adding `0.001` until the mtime changes.

**Comment by hobarrera** [comment]
This new change should be safer.

**Comment by untitaker** [comment]
Hm, now this will return None on second-precision fs I think

**Comment by untitaker** [comment]
Suggestion:

    i = 0.000001
    while True:
        a = touch_and_mtime()
        sleep(i * 1.1)
        b = touch_and_mtime()
        if a != b:
            return i * 1.1
        i *= 10

**Comment by hobarrera** [comment]
Returning `i * 10` sounds safer because we're sure our sleeps are an order of magnitude above the timestamp precision. 
This is 10ms on most modern systems, so the entire test suite doesn't even increase in a single second.

**Comment by hobarrera** [comment]
As another alternative, we can `mock` the result of `os.stat`. This sounds like the best idea, and doesn't involve any sleeping.

**Comment by untitaker** [comment]
>Returning i * 10 sounds safer because we're sure our sleeps are an order of magnitude above the timestamp precision.

And it's 10 seconds on a system with second-precision

**Comment by geier** [comment]
I don't like mocking this, I'd go with untitaker's solution and wait till it fails somewhere again.

**Comment by hobarrera** [comment]
Back to this PR then, [this](https://github.com/pimutils/khal/pull/577#issuecomment-280055820) suggestion won't work.

Assume that precision is 100ms:
* Current time is 11:42:20.99999
* Record `a`
* Sleep 11ms
* Record `b`
* We noticed the `mtime` differ
* Okay, we return 11ms (WRONG!)

The chances of this happening are actually about 10%, so it's something worth considering.

This should work though:

```python
i = 0.000001
while True:
    a = touch_and_mtime()
    sleep(i)
    b = touch_and_mtime()
    sleep(i)
    c = touch_and_mtime()
    if a != b != c:
        return i * 1.1
    i *= 10
```

This fixes the above scenario. Chances of failure because of the current time are practically inexistant.

---

Note (mostly for the fun of it): This can fail on [leap seconds](https://en.wikipedia.org/wiki/Leap_second). Seriously, I don't care this means the loop has to be run *at an exact time* (with sub-second precision) in a window that only available once every year.

**Comment by untitaker** [comment]
Good point and I agree that your solution is excellent.

**Comment by hobarrera** [comment]
Thanks! PR updated.

**Comment by untitaker** [comment]
We probably should raise an exception if `i > 10`

**Comment by geier** [comment]
Thank you both! 

Am 18. Februar 2017 18:53:34 MEZ schrieb Hugo Osvaldo Barrera <notifications@github.com>:
>Merged #577.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/pull/577#event-968070359

-- 
Sent from my phone. Please excuse my brevity.

**Pull request merged**
