### PR TITLE
day-format does not print empty string

### PR DESCRIPTION
**Pull request by youngmoney**
as the title says `--day-format ''` will not print any day headers

### CODE REVIEW

**Comment by geier** [comment]
@youngmoney Please fix the test (or even better, also write a new one)

**Comment by geier** [comment]
also: do you know why --day-format '\n' does print an actual `\n`? Some click.echo magic?

**Comment by youngmoney** [comment]
the \n is actually a pythonism/other languages but not in bash in bash it is very literal. In bash one must use a real newline (and that works). It might be true that if you change the config a '\n' might work. (an assumption was made you are using bash, as that is my case)

**Comment by youngmoney** [comment]
I'll write the test soon!

**Comment by geier** [comment]
I think it's rather a Cism than a pythonism. But it looks like python escapes it itself. There is the `unicode_escape` escoding for usages like this, not sure if it is a good idea to actually use it though.

```
% echo 'x\ny'
x
y
% cat test2.py
import sys

arg = sys.argv[1]
print(arg)
print(arg.encode('utf-8').decode('unicode_escape'))
% python test2.py 'x\ny'
x\ny
x
y
```

**Comment by geier** [comment]
sorry, hit the wrong button.

**Comment by youngmoney** [comment]
I think we should leave it for now, unless we want to make \n usable everywhere

**Comment by youngmoney** [comment]
I've fixed/added a test

I also as a bash sidenote:
```
$ echo 'x\ny'
x\ny
```

**Comment by geier** [comment]
Thanks! (and I agree, we would need to make `\n` usable everywhere, but while nobody asks for it, it's not really worth discussing it).

**Pull request merged**
