### PR TITLE
Set microsoft busy status

### PR DESCRIPTION
**Pull request by whit2333**
- The status is set to busy by default for microsoft.
- Need to add option to set value.

### CODE REVIEW

**Comment by geier** [comment]
@whit2333 Thank you for helping improve khal.

I am not sure, if setting all calendar entries to busy is the right approach. IMO the busy status should be editable in ikhal and probably in the command line version as well.

**Comment by geier** [comment]
closing and reopening to re-run tests

**Comment by WhyNotHugo** [comment]
See: https://github.com/pimutils/khal/pull/1220

**Comment by geier** [comment]
please re-open if there is any interest in working on this.

**Pull request closed without merging**
