### PR TITLE
ikhal: Do not crash when a extended ascii char is pressed with non ut…

### PR DESCRIPTION
**Pull request by sithglan**
…f-8 locale

Overwrite `_normalize_to_caption` from `urwid/widget.py` Edit class in ExtendedEdit
to use `sys.stdin.encoding` instead of `ascii` when normalizing text.

Howto reproduce:
- `export LC_CTYPE=de_DE@euro`
- start khal
- press <kbd>n</kbd> to crate a new event
- type `ü`

The following crash happens:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/khal-v0.6.0-py2.7.egg/khal/ui/__init__.py", line 653, in start_pane
    loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 669, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 706, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 390, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 490, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1124, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2265, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python2.7/dist-packages/khal-v0.6.0-py2.7.egg/khal/ui/__init__.py", line 577, in keypress
    return super(EventEditor, self).keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2265, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python2.7/dist-packages/khal-v0.6.0-py2.7.egg/khal/ui/widgets.py", line 85, in keypress
    return super(ExtendedEdit, self).keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 1474, in keypress
    self.insert_text(key)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 1398, in insert_text
    text = self._normalize_to_caption(text)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 1415, in _normalize_to_caption
    return text.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 0: ordinal not in range(128)
```

This patch fixes that.

### CODE REVIEW

**Comment by sithglan** [comment]
Related: https://github.com/wardi/urwid/pull/138

**Comment by untitaker** [comment]
I suspect that the bug lies somewhere else.

Urwid's unicode model seems to be that anything passed as bytestring has an undefined encoding, and is therefore treated as ASCII, which causes crashes but avoids mojibake. So I think the problem is rather that something further up the stacktrace doesn't convert to unicode soon enough.

**Comment by sithglan** [comment]
Looking at the code of urwid/widget.py urwid either handles text in bytes or unicode. Since I have ISO-8859-15 (de_de@euro) locale and not a unicode. It does handle it in bytes. The job of the _normalize_to_caption is to convert from the input type to the type of the self.caption. According to the comment of the function. Since my input type is ISO-8859-15 it should detect the input type correctly and this is exactly what this patch does according to my understanding. But I think the best person to handle the bug is wardi and I have reported this bug also upstream. At least this patch fixes the problem for me and I'll use it until something better comes along. Converting to UTF-8 is not an option for me.

**Comment by untitaker** [comment]
>Since I have ISO-8859-15 (de_DE@euro) locale and not a unicode. It does handle it in bytes.

The unicode string type is not bound to the original encoding at all -- it doesn't matter what the original encoding was.

>Changing my terminal to UTF-8 is not an option for me.

I wonder why?

**Comment by sithglan** [comment]
> The unicode string type is not bound to the original encoding at all -- it doesn't matter what the original encoding was.

The problem I'm experiencing is related that to that it does matter what the original encoding is. Because it is assumed to be ascii while it isn't. So the encoding fails and the programm crashes. Once it is converted, I agree with you.

> I wonder why?

I'm used to a de_DE@euro environment for 15 years now and I don't miss anything. The only reason to switch to unicode would be khal. But I rather fix khal than convert to UTF-8. I like ISO-8859-15 and it has everything I currently need.

**Comment by untitaker** [comment]
>Once it is converted, I agree with you.

The point is that it should be converted earlier because this piece of code can't know that this bytestring comes from stdin. The same function is used in `set_edit_text`, which might take a bytestring from *any resource* which is not bound to the locale.

**Comment by sithglan** [comment]
You're right. Than chardet or a similiar python library should be used to detect the correct encoding.
https://pypi.python.org/pypi/chardet Do you agree?

**Comment by sithglan** [comment]
Or we could make it for our use case configurable and use the conf['locale']['encoding'] configuration variable. I prepared a patch earlier that does that, but did not submit it because I thought this would be right thing to do.

**Comment by untitaker** [comment]
The string should just be decoded with `sys.stdin.encoding` further up the call stack (in `keypress` or so).

**Comment by geier** [comment]
I believe khal should work whatever encoding you use, but as I use utf-8 (and I believe that should be the default).

Do I see this correctly: this  should be fixed in urwid and this is a temporary fix so khal is usable for the time being? (I fully support this).

**Comment by sithglan** [comment]
Yes, but @unitaker has good point. I did the wrong assumption. And the encoding should be fixed in keypress and not in _normalize_to_caption. But I would wait until @wardi gives his input to this because he will probably put a final fix in urwid and than we can copy the fix into khal until urwid is released and distributed through distributions enough.

**Comment by geier** [comment]
@sithglan did you get any feedback from the folks at urwid?

**Comment by wardi** [comment]
@geier no, I've been slow, will look at it now

**Comment by geier** [comment]
@sithglan is this still an issue (we we need to fix in khal)?

**Comment by sithglan** [comment]
Hello Christian,

> @sithglan is this still an issue (we we need to fix in khal)?

at the moment it does not even start for me: I tried khal a few weeks back and
than it also did not start for me because it did not like my locale.

My locale is:

(infra) [~] locale
LANG=C
LANGUAGE=
LC_CTYPE=de_DE@euro
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

My locale in khal used to be:

(infra) [~] cat .khal/khal.conf
[calendars]
[[Thomas Glanzmann]]
path = ~/.calendars/calendar/
color = light blue

# [locale]
# local_timezone= Europe/Berlin
# default_timezone= Europe/Berlin
# timeformat= %H:%M
# dateformat= %Y-%m-%d
# longdateformat= %Y-%m-%d
# datetimeformat= %Y-%m-%d %H:%M
# longdatetimeformat= %Y-%m-%d %H:%M
# unicode_symbols = False
# encoding = ISO-8859-15
# weeknumbers = left

[default]
days = 1
default_calendar = Thomas Glanzmann

(infra) [~] virtualenv ~/khal
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/sithglan/khal/bin/python2
Also creating executable in /home/sithglan/khal/bin/python
Installing setuptools, pip...done.
(infra) [~] ~/khal/
bin/     include/ lib/     local/
(infra) [~] ~/khal/bin/
easy_install*     pip*              pip2.7*           python2*
easy_install-2.7* pip2*             python@           python2.7@
(infra) [~] ~/khal/bin/pip
pip*    pip2*   pip2.7*
(infra) [~] ~/khal/bin/pip install khal
Downloading/unpacking khal
  Downloading khal-0.8.1-py2.py3-none-any.whl (91kB): 91kB downloaded
Downloading/unpacking tzlocal>=1.0 (from khal)
  Downloading tzlocal-1.2.2.tar.gz
  Running setup.py (path:/tmp/pip-build-L22mQ0/tzlocal/setup.py) egg_info for package tzlocal

Downloading/unpacking icalendar (from khal)
  Downloading icalendar-3.9.2.tar.gz (66kB): 66kB downloaded
  Running setup.py (path:/tmp/pip-build-L22mQ0/icalendar/setup.py) egg_info for package icalendar

    warning: no previously-included files matching '*.pyc' found under directory 'src/icalendar'
    warning: no previously-included files matching '*~' found under directory 'src/icalendar'
Downloading/unpacking pyxdg (from khal)
  Downloading pyxdg-0.25.tar.gz (48kB): 48kB downloaded
  Running setup.py (path:/tmp/pip-build-L22mQ0/pyxdg/setup.py) egg_info for package pyxdg

Downloading/unpacking pytz (from khal)
  Downloading pytz-2016.3-py2.py3-none-any.whl (479kB): 479kB downloaded
Downloading/unpacking vdirsyncer (from khal)
  Downloading vdirsyncer-0.9.3-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking python-dateutil (from khal)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB): 201kB downloaded
Downloading/unpacking urwid (from khal)
  Downloading urwid-1.3.1.tar.gz (588kB): 588kB downloaded
  Running setup.py (path:/tmp/pip-build-L22mQ0/urwid/setup.py) egg_info for package urwid

    warning: no files found matching 'CHANGELOG'
Downloading/unpacking configobj (from khal)
  Downloading configobj-5.0.6.tar.gz
  Running setup.py (path:/tmp/pip-build-L22mQ0/configobj/setup.py) egg_info for package configobj

Downloading/unpacking click>=3.2 (from khal)
  Downloading click-6.6.tar.gz (283kB): 283kB downloaded
  Running setup.py (path:/tmp/pip-build-L22mQ0/click/setup.py) egg_info for package click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./khal/lib/python2.7/site-packages (from icalendar->khal)
Downloading/unpacking requests-toolbelt>=0.4.0 (from vdirsyncer->khal)
  Downloading requests_toolbelt-0.6.0-py2.py3-none-any.whl (48kB): 48kB downloaded
Downloading/unpacking atomicwrites>=0.1.7 (from vdirsyncer->khal)
  Downloading atomicwrites-1.0.0-py2.py3-none-any.whl
Downloading/unpacking requests>=2.4.1,!=2.9.0 (from vdirsyncer->khal)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Downloading/unpacking click-log>=0.1.3 (from vdirsyncer->khal)
  Downloading click_log-0.1.4-py2.py3-none-any.whl
Downloading/unpacking lxml>=3.1 (from vdirsyncer->khal)
  Downloading lxml-3.6.0.tar.gz (3.7MB): 3.7MB downloaded
  Running setup.py (path:/tmp/pip-build-L22mQ0/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.6.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28

    warning: no previously-included files found matching '*.py'
Downloading/unpacking click-threading>=0.1.2 (from vdirsyncer->khal)
  Downloading click_threading-0.1.2-py2.py3-none-any.whl
Downloading/unpacking six>=1.5 (from python-dateutil->khal)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: khal, tzlocal, icalendar, pyxdg, pytz, vdirsyncer, python-dateutil, urwid, configobj, click, requests-toolbelt, atomicwrites, requests, click-log, lxml, click-threading, six
Compiling /tmp/pip-build-L22mQ0/khal/khal/ui/widgets.py ...
  File "/tmp/pip-build-L22mQ0/khal/khal/ui/widgets.py", line 383
    def __init__(self, *args, EditWidget=ExtendedEdit, validate=False, **kwargs):
                                       ^
SyntaxError: invalid syntax

  Running setup.py install for tzlocal

  Running setup.py install for icalendar

    warning: no previously-included files matching '*.pyc' found under directory 'src/icalendar'
    warning: no previously-included files matching '*~' found under directory 'src/icalendar'
  Running setup.py install for pyxdg

  Running setup.py install for urwid
    building 'urwid.str_util' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -fPIC -I/usr/include/python2.7 -c source/str_util.c -o build/temp.linux-x86_64-2.7/source/str_util.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Os build/temp.linux-x86_64-2.7/source/str_util.o -o build/lib.linux-x86_64-2.7/urwid/str_util.so

    warning: no files found matching 'CHANGELOG'
  Running setup.py install for configobj

  Running setup.py install for click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
  Running setup.py install for lxml
    Building lxml version 3.6.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Os build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so
    building 'lxml.objectify' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Os -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.objectify.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Os build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/objectify.so

Successfully installed khal tzlocal icalendar pyxdg pytz vdirsyncer python-dateutil urwid configobj click requests-toolbelt atomicwrites requests click-log lxml click-threading six
Cleaning up...
(infra) [~] ~/khal/bin/khal
Traceback (most recent call last):
  File "/home/sithglan/khal/bin/khal", line 7, in <module>
    from khal.cli import main_khal
  File "/home/sithglan/khal/local/lib/python2.7/site-packages/khal/cli.py", line 25, in <module>
    from shutil import get_terminal_size
ImportError: cannot import name get_terminal_size

Cheers,
        Thomas

**Comment by geier** [comment]
It looks like you are using python 2.7, but we dropped support for python 2 with the latest release. Please try "upgrading" to python 3.

**Comment by hobarrera** [comment]
> It looks like you are using python 2.7, but we dropped support for python 2 with the latest release. Please try "upgrading" to python 3.

For the record, python2 and python3 can be co-installed.

**Comment by sithglan** [comment]
Hello Christian,

> It looks like you are using python 2.7, but we dropped support for
> python 2 with the latest release. Please try "upgrading" to python 3.

virtualenv --no-site-packages --distribute -p /usr/bin/python3 ~/khal
~/khal/bin/pip install khal

with python3 I get:

Traceback (most recent call last):
  File "/home/sithglan/khal/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sithglan/khal/lib/python3.4/site-packages/khal/cli.py", line 247, in cli
    ctx.invoke(cli.commands[command])
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sithglan/khal/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sithglan/khal/lib/python3.4/site-packages/khal/cli.py", line 279, in calendar
    week=week,
  File "/home/sithglan/khal/lib/python3.4/site-packages/khal/controllers.py", line 164, in calendar
    bold_for_light_color=bold_for_light_color)
  File "/home/sithglan/khal/lib/python3.4/site-packages/khal/calendar_display.py", line 170, in vertical_month
    weekheaders = get_weekheader(firstweekday)
  File "/home/sithglan/khal/lib/python3.4/site-packages/khal/calendar_display.py", line 47, in get_weekheader
    return _calendar.formatweekheader(2)
  File "/usr/lib/python3.4/calendar.py", line 301, in formatweekheader
    return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
  File "/usr/lib/python3.4/calendar.py", line 301, in <genexpr>
    return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
  File "/usr/lib/python3.4/calendar.py", line 515, in formatweekday
    with different_locale(self.locale):
  File "/usr/lib/python3.4/calendar.py", line 494, in __enter__
    _locale.setlocale(_locale.LC_TIME, self.locale)
  File "/home/sithglan/khal/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Cheers,
        Thomas

**Comment by geier** [comment]
This new error is caused by pyhon not (properly?) supporting the `de_DE.ISO8859-15` (`de_DE@euro`) locale. 

when starting python with `LC_CTYPE=de_DE@euro python` I get the following:

```python
>>> import locale
>>> locale.getdefaultlocale()
('de_DE', 'ISO8859-15')
>>> locale.setlocale(locale.LC_ALL, '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/home/cg/.virtualenvs/khal/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

which is equivalent to
```python
>>> locale.setlocale(locale.LC_ALL, 'de_DE@euro')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/home/cg/.virtualenvs/khal/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

while `de_DE.UTF-8` works fine:

```python
>>> locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')
'de_DE.UTF-8'
```

**Comment by geier** [comment]
The way we are currently getting the locale is pretty stupid, but the error won't go away. What we want to do is getting the weekheaders in the users current locale. We can produce that error like this:

```python
import calendar
calendar.LocaleTextCalendar(0, 'de_DE.iso8859-15').formatweekheader(2)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-74512058f819> in <module>()
----> 1 calendar.LocaleTextCalendar(0, 'de_DE.iso8859-15').formatweekheader(2)

/usr/lib/python2.7/calendar.pyc in formatweekheader(self, width)
    299         Return a header for a week.
    300         """
--> 301         return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
    302 
    303     def formatmonthname(self, theyear, themonth, width, withyear=True):

/usr/lib/python2.7/calendar.pyc in <genexpr>((i,))
    299         Return a header for a week.
    300         """
--> 301         return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
    302 
    303     def formatmonthname(self, theyear, themonth, width, withyear=True):

/usr/lib/python2.7/calendar.pyc in formatweekday(self, day, width)
    514 
    515     def formatweekday(self, day, width):
--> 516         with TimeEncoding(self.locale) as encoding:
    517             if width >= 9:
    518                 names = day_name

/usr/lib/python2.7/calendar.pyc in __enter__(self)
    492     def __enter__(self):
    493         self.oldlocale = _locale.getlocale(_locale.LC_TIME)
--> 494         _locale.setlocale(_locale.LC_TIME, self.locale)
    495         return _locale.getlocale(_locale.LC_TIME)[1]
    496 

/usr/lib/python2.7/locale.pyc in setlocale(category, locale)
    581         # convert to string
    582         locale = normalize(_build_localename(locale))
--> 583     return _setlocale(category, locale)
    584 
    585 def resetlocale(category=LC_ALL):
```

while again `de_DE.UTF-8` works:

```python
In [3]: calendar.LocaleTextCalendar(0, 'de_DE.UTF-8').formatweekheader(2)
Out[3]: u'Mo Di Mi Do Fr Sa So'
```

[Tracing that back even further](https://github.com/python/cpython/blob/2d264235f6e066611b412f7c2e1603866e0f7f1b/Modules/_localemodule.c#L109) it looks like `locale.h`'s `setlocale()` is failing here. Therefore I'm quite surprised that @sithglan has no problems with that locale setting anywhere else.

**Comment by geier** [comment]
Possibly, converting `de_DE@euro` to `de_DE.iso8859-15` (which python does internally) is just wrong (in your case).

@sithglan, can you try:
```
import calendar
calendar.LocaleTextCalendar(0, 'de_DE.iso8859-15').formatweekheader(2)
```

and 
```
import calendar
calendar.LocaleTextCalendar(0, 'de_DE@euro').formatweekheader(2)
```
?

Also, do you know whan encoding `de_DE@euro` really is in your case?

**Comment by untitaker** [comment]
@geier do you have the locale enabled in `/etc/locale.conf`/`localectl`? That would explain the "unsupported locale" you're getting.

**Comment by sithglan** [comment]
Hello Christian,

* Christian Geier <notifications@github.com> [2016-04-28 17:49]:
> Possibly, converting `de_DE@euro` to `de_DE.iso8859-15` (which python does internally) is just wrong (in your case).

> @sithglan, can you try:
> ```
> import calendar
> calendar.LocaleTextCalendar(0, 'de_DE.iso8859-15').formatweekheader(2)
> ```

> and 
> ```
> import calendar
> calendar.LocaleTextCalendar(0, 'de_DE@euro').formatweekheader(2)
> ```
> ?

(infra) [~] python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import calendar
>>> calendar.LocaleTextCalendar(0, 'de_DE.iso8859-15').formatweekheader(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/calendar.py", line 301, in formatweekheader
    return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
  File "/usr/lib/python3.4/calendar.py", line 301, in <genexpr>
    return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
  File "/usr/lib/python3.4/calendar.py", line 515, in formatweekday
    with different_locale(self.locale):
  File "/usr/lib/python3.4/calendar.py", line 494, in __enter__
    _locale.setlocale(_locale.LC_TIME, self.locale)
  File "/usr/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
>>> import calendar
>>> calendar.LocaleTextCalendar(0, 'de_DE@euro').formatweekheader(2)
'Mo Di Mi Do Fr Sa So'

> Also, do you know whan encoding `de_DE@euro` really is in your case?

(infra) [~] grep -v '^#' /etc/locale.gen
de_DE ISO-8859-1
de_DE.UTF-8 UTF-8
de_DE@euro ISO-8859-15
en_US ISO-8859-1
en_US.UTF-8 UTF-8
en_DK.UTF-8 UTF-8
fr_FR ISO-8859-1

I think ISO-8859-15.

Cheers,
        Thomas

**Comment by youngmoney** [comment]
is this still a problem?

**Comment by sithglan** [comment]
Hello,

> is this still a problem?

yes, the maintainers do not care if there software is not working on a
non utf8 environment. So in addition to this problem khal currently does
not start at all in a non utf8 environment:

...
locale.Error: unsupported locale setting

Cheers,
        Thomas

**Comment by untitaker** [comment]
Thomas, I'd apprechiate if you would keep any such accusations to yourself.

On 6 July 2016 11:07:51 EEST, Thomas Glanzmann <notifications@github.com> wrote:
>Hello,
>
>> is this still a problem?
>
>yes, the maintainers do not care if there software is not working on a
>non utf8 environment. So in addition to this problem khal currently
>does
>not start at all in a non utf8 environment:
>
>...
>locale.Error: unsupported locale setting
>
>Cheers,
>        Thomas
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/pull/224#issuecomment-230705825

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by youngmoney** [comment]
Hi Thomas,

While I understand your frustration I think that it is important to understand that the time and effort required to support non-utf8 systems is not trivial. Since most people are on utf8 it makes sense to spend time fixing the 49 other current issues. If you could find a simple solution that can be maintained with very little time (and write tests) then I would be more than happy to help you bring it into master. However I have very little understanding of the problems that come with the encoding change.

Thanks,
Taylor

**Pull request closed without merging**
