### PR TITLE
Prevent saving empty location and description in ICS file

### PR DESCRIPTION
**Pull request by pfertyk**
This should fix issue #436.

### CODE REVIEW

**Comment by geier** [comment]
Looks good, thanks! Please also add yourself to AUTHORS.txt, I don't believe you are in there yet, are you?

**Comment by geier** [comment]
While thinking about this, we also need to remove the current location/description if the update changes this to `''`.

**Comment by geier** [comment]
Sorry, misclicked.

**Comment by geier** [comment]
*Should* work something like this: self._vevents.pop('LOCATION'), but a test would be great as well.

**Comment by pfertyk** [comment]
I added more tests for removing the existing location/description if set to empty and I implemented this feature.

**Comment by geier** [comment]
Looks good. Can you rebase onto master? (git rebase master)

**Comment by pfertyk** [comment]
I rebased (and added a missing email address). Could you confirm that this is what you meant?

**Comment by geier** [comment]
Yes, that's what I meant. Thanks!

**Pull request merged**
