### PR TITLE
ikhal: layout improvements

### PR DESCRIPTION
**Pull request by geier**
This PR changes (improves?) the look of ikhal. For now the help pane pane was changed and the alignments and attributes in the editor. This should also make more elements in ikhal themeable via the color themes.

### CODE REVIEW

**Comment by geier** [comment]
Before: 
image

after: 
image

**Comment by geier** [comment]
before: 
image

after:
image

**Comment by geier** [comment]
Button background color should probably be improved upon.

**Review by WhyNotHugo — APPROVED** [review]
LGTM. At a glance, it all looks much tidier, even if all the changes are quite subtle themselves.

**Comment by WhyNotHugo** [comment]
No, definitely not. PR is good as-is.

**Pull request merged**
