### PR TITLE
update_birthday: Augment sqlite3.IntegrityError with additional info

### PR DESCRIPTION
**Pull request by madduck**
khal wasn't actually expecting a sqlite3.IntegrityError, so this
converts it to an UpdateError, while also providing some more
information about the addressbook record for which we're creating
a birthday event.

Signed-off-by: martin f. krafft <madduck@madduck.net>

### CODE REVIEW

**Comment by madduck** [comment]
Hm, `BUILD=style` failed, and I think this must be due to the very long string. I am not sure how else you'd prefer it, and I actually consciously put it all into one line to not weigh too heavy on the code otherwise.

Please advise…

**Comment by madduck** [comment]
I'd be happy to try to provide a test-case too, but first I need to understand the issue.

Is it that the assumption is that a birthday doesn't change, and so `INSERT` is fine? What happens in the case of typos?

**Comment by madduck** [comment]
There, fixed the long line after finding out that Python indeed supports `("foo"\n"bar")` concatenation.

**Review by geier — APPROVED** [review]

**Comment by geier** [comment]
only 4 years later: let's get this merged, better error messages are always good. @madduck do you want to rebase this or should I?

**Pull request merged**
