### PR TITLE
Improve sorting of events

### LINKED ISSUE #976: khal interactive allday events at bottom of day.
`khal list` will show an agenda with  any  all  day events  at the  top  of the day (which seems right), while `khal interactive` shows events listed at the bottom of  the day (which seems counter intuitive to me) . Tried poking around the docs to see if there was some setting I missed and I couldn't seem to find one.

### LINKED ISSUE #981: Proposal: Improve sorting
Currently events are sorted by start date/time only. I would like to change to sort by start, then end, then summary.

Comments welcome.

### PR DESCRIPTION
**Pull request by d7415**
Sort by start, then end, then summary.

Closes #981. Fixes #976.

This may need some refactoring, maybe some comments and probably needs some tests. But the concept should be ready for review.

### CODE REVIEW

**Comment by geier** [comment]
Looks sensible, do you have the time to write a test? If not, I could do it.

**Comment by d7415** [comment]
I'll see what I can manage tomorrow. It's been a while since I've looked at this, but I guess it should just be a set of events to check each level and ideally conflicting types.

**Comment by d7415** [comment]
Rebased on master and added tests.

**Comment by geier** [comment]
Awesome, thanks!

**Pull request merged**
