### PR TITLE
#805 : Add ability to define default duration

### PR DESCRIPTION
**Pull request by ephase**
For float and allday event, this can be set on config file : 
```
[default]
# Define the defaut duration for an allday event
default_duration_date = 1d

# Define the default duration for an event
default_duration_datetime = 1h
```

### CODE REVIEW

**Comment by madduck** [comment]
I just had a look at this, and tried it out, and it's working perfectly.

The only feedback I have is:

* I am unsure of the use case to override the duration of an all-day event.
* I find `default_duration_datetime` to be confusing, possibly exposing too much implementation detail. How about `default_event_duration` instead?

**Comment by Jikhai** [comment]
hey,
about all-day events, we thought it would be useful for uses like an on-call schedule, where you might want to schedule someone on a post for 36 or more hours instead of 24,
while keeping the other field for shorter events.

As for variable names, you are absolutely right, your idea sounds way better, we will adjust the PR to use ```default_event_duration``` and  ```default_dayevent_duration```

**Comment by Jikhai** [comment]
Hi, 
We've taken care of the changes you requested, in both ```khal.spec``` and ```CHANGELOG.rst```.
We've also added our names to the Authors file (of all 5 of us, since it's a group effort).
All these changes are in the PR, ready for review.

**Comment by geier** [comment]
Thank you all then!

**Pull request merged**
