### PR TITLE
Add a warning for the special case where RRULE:UNTIL is before DTSTART (#771,#790,#972)

### PR DESCRIPTION
**Pull request by d7415**
#771, #790 and #972 all refer to events where the `RRULE:UNTIL` was before the event's `DTSTART`. This patch will stop khal from attempting to handle such events and will log a warning about it.

### CODE REVIEW

**Comment by d7415** [comment]
I'm not entirely sure that this is the best option. Part of me thinks we should still raise `UnsupportedRecurrence`, but add the message for context. Ideas welcome.

**Review by ephase — APPROVED** [review]
Seems good for me, tested with my own calendars all work like a charm.

**Comment by d7415** [comment]
Thanks @ephase. Do you have any thoughts about raising the UnsupportedRecurrence? I'm leaning towards no as I've already said `This event will not be available in khal` so a Traceback may just be distracting. I'll probably wait a week or so before merging to allow for other opinions though.

**Comment by ephase** [comment]
I'm ok with you, Exception is not necessary here, your message is enough.

**Pull request merged**
