### PR TITLE
Add cli option for eol character for khal_list

### PR DESCRIPTION
**Pull request by greole**
in some situations I prefer to list events next to each other and save some screen space.

### CODE REVIEW

**Comment by geier** [comment]
Hi @greole and thank you for making khal better!

Would you be using this interactively or with a script? (In the latter case, some awking should do the trick). 

I'm actually a bit hesitant to accept this, because adding this new option also increases the complexity. 
@hobarrera @untitaker opinions?

If we are to merge this, we some tests would be really nice though.

**Comment by untitaker** [comment]
I think you can just pipe through a command which replaces newlines with something else...

**Comment by greole** [comment]
@geier @untitaker  valid points!

However ultimately it would be great if one could lists events like

      Sunday:  Event 1 Event 2
      Monday:  Event 3 Event 4  Event 5
      Tuesday: Event 6

Anyways,  thanks a lot for khal :+1:!

**Comment by geier** [comment]
This looks really good, especially if you have only a few events, perhaps we *should* get this in, as most other aspects of event printing are already fully configurable. 

As I said above, if you have the time, please write some tests for the new behavior.

**Comment by untitaker** [comment]
Then I think we should call it `event-separator` or something like that, not eol.

**Comment by greole** [comment]
I could imagine different solutions. For example the separators `A`,`B` and `C` in 

      Sunday A Event 1 B Event 2 C
      Monday A Event 3 B Event 4 B Event 5 C
      Tuesday A Event 6 C
could be made modifiable. Then if A=:\n and B=, and C=\n

      Sunday:
      Event  1, Event 2
      Monday:
      Event 3, Event 4, Event 5
      Tuesday:
      Event 6
or 

      Sunday: Event 1 Event 2
      Monday: Event 3 Event 4 Event 5
      Tuesday: Event 6

for  A=: and B= and C=\n etc. Concerning the CLI, the args could be specified as

**Version1**
      --event-separator "\n" "," "\n" # needs many colons 

and click seems not to support a mixture of given and default options, hence
     
      --event-separator "\n" "," # invalid
**Version2**
Some kind of formatting string

      --event-separator "\n, ,\n" # coma separated separators
or something that can be parsed with regex like

     --event-separator "{\n}{,}{\n}"

**Version3**
 Each separator would get an additional option.

What do you think?

**Comment by geier** [comment]
I believe that if we are going to do this, we should go all the way and make it completely configurable (as you suggested).

What way to specify those works best, I have no idea. Feel free to experiment.
We could think about removing option A (and make it a part of the day-format option), but than it would be less consistent with B and C.

**Comment by greole** [comment]
Ok in the latest PR newlines can be added explicitly by the  `day-format`  parameter.  `B` can be specified by --event-separator and a true `C` would need a new option if really necessary . A line break after each event  can also be specified by the `format` arg. I wrote a first (basic) test for the event-separator and adapted some tests.

**Comment by hobarrera** [comment]
What's the status for this?

**Comment by geier** [comment]
Closing for row, reopen this (or a new PR if you are still interested in this).

**Comment by hobarrera** [comment]
Rather than include such complex settings and flags for so much output customization, maybe we can do something similar to todoman's `--porcelain`, which outputs everything in an easily-parsable format (JSON), so scripts can reformat this as needed.

I'd use this, for example, to show my next event in my i3 status bar. Any other weird formatting need can just be a wrapper around `khal --porcelain`.

I'll try to see if I can work on this after I've finished #611

**Pull request closed without merging**
