### PR TITLE
Add 'khal export' command

### PR DESCRIPTION
**Pull request by tpikonen**
I needed to create a webcal .ics file from a calendar and could not figure out an easy way to do it. So, I ended up adapting 'khal list' to output the raw ics strings of events, with the headers of the intermediate events trimmed out. The result is this PR implementing 'khal export'. 

The code is not tested much, but works for me. If this has a chance of being accepted, I can work on it some more and add tests, documentation etc.

### CODE REVIEW

**Comment by matt-snider** [comment]
I think this is an important thing to have! The issue referenced above is one good use case.

A few thoughts:

* A `--uuid` (or `--uid` to stay consistent) filter to specify a single event unambiguously 
* The date range filters seem more fitting as options than arguments, since as with `--uid`, more may be added later, or you may not want to filter by date at all, but by description, etc. 
* Make the outfile the only argument. If it is omitted it should print to stdout

**Comment by matt-snider** [comment]
Another thing to consider, is whether it may make more sense to just extend the `search` command with this functionality. This command is actually just a way to filter events and output them in a particular format.

I think this would entail adding at least the following to `search`:

* `--output [ics, string]`
* `--date-range ...`

Adding `--uid` as described in the previous comment might also be useful.

**Comment by chess-seventh** [comment]
I think having either the `--uid` parameter passed in the `search` or the `export` command would be great. Having this attribute for scripting (FWIW) would be indeed an asset.

Is there something to do/add in order to get this PR in merged? I'll gladly try to help! 
pinging new maintainer @ephase :)

**Comment by ephase** [comment]
@chess-seventh I'm agree with you about `--uid` for search or export. Code seems good but as I'm newbie python developer, I think @d7415 should look into it.

@tpikonen could you add an option for uid export, if not I could try.

**Comment by d7415** [comment]
> I think @d7415 should look into it. I'll try to test it this evening.

This one's on my list to look at. Probably next on my list. I don't know when that'll be though.

**Comment by d7415** [comment]
We have an option for output. Currently this will overwrite the file if one exists.
Options:
- Document it, leave it as-is
- Prompt the user if the file exists
- Always output to stdout

I'm leaning to the first option, because it's easy. The second might be nicer, but then we'd need to go interactive, which limits scripting options. I only expect to use it with stdout (if at all), but the flexibility is nice.

**Comment by WhyNotHugo** [comment]
Fourth option is to only overwrite it `--force` is passed. Safe, and script friendly.

**Comment by d7415** [comment]
> Fourth option is to only overwrite it `--force` is passed. Safe, and script friendly.

True. It's a bit messy needing two commands just to write a file though. And "force" seems a bit strong as a verb.

**Comment by madduck** [comment]
But `--force` is the "industry-standard" and it's what pretty much all other commands use in this situation.

**Comment by d7415** [comment]
I mostly agree - I'd say industry standard is probably "just overwrite it" though!

But this is why I raised it here before doing starting work in any direction :)

**Comment by madduck** [comment]
Yeah, I guess it depends on whether you clobber by default, or not. I think it's better to use `--force` in this case.

**Comment by d7415** [comment]
Looks like a consensus.

Next question - Should we default other messages to stderr if we're outputting to stdout? Somewhat out of scope, but should we do that anyway? Or just recommend it in the docs using `-l`/`--logfile`?

**Comment by WhyNotHugo** [comment]
For non-fatal output, we should use `stderr`, since one might want verbose scripts, but the output to be piped into something else.

For fatal output... I've no strong opinion either way. Probably writing to `stderr` reduces the changes of unexpected misbehaviour when piping, but people _should_ use stuff like `set -o pipefail`, or checking exit codes when writing scripts that pipe in general.

**Comment by geier** [comment]
As nobody continued the work on this, I'll close it for now.

**Pull request closed without merging**
