### PR TITLE
add end-necessary to event.format

### PR DESCRIPTION
**Pull request by youngmoney**
simple fix for #455

comment on style/name/etc

### CODE REVIEW

**Comment by geier** [comment]
good for now, only some docs please. And you might want to remove the idiotic defaultdict I put in there (or I will later, no rush).

**Comment by youngmoney** [comment]
I've added documentation, as a side note I dont thing the defaultdict is
"idiotic", It is certainly fine to have it there as incorrect format strings
will not error, but instead just be empty strings

**Comment by geier** [comment]
I'm unsure, the problem is, you might not notice typos, or, as happened to me in one of our last conversations, I thought `{end-necessary}` would already exist, but was just bugged.

**Comment by youngmoney** [comment]
I'll fix this in day format #457

**Pull request merged**
