### PR TITLE
Make sure urwid vesrion is 2.6.15 else issue #1357

### PR DESCRIPTION
**Pull request by gachikuku**
Upgrading urwid fixes issue #1357.

### CODE REVIEW

**Comment by mschilli87** [comment]
Just wanted to confirm this fixes the issue for me as well.

**Review by WhyNotHugo — COMMENTED** [review]
The changelog for "not yet released" says "UPDATED REQUIREMENT urwid is now required >= 2.1.0". We ought to update that entry.

**Review by WhyNotHugo — APPROVED** [review]
LGTM

**Comment by WhyNotHugo** [comment]
Feel free to add yourself to `AUTHORS.txt`.

**Comment by WhyNotHugo** [comment]
Thanks!

**Pull request merged**
