### PR TITLE
increment width of the month column. fix #653

### LINKED ISSUE #653: Broken design for months that have long abreviated names
With a french locale, this is what ikhal looks like (note the blank lines for juil. and others) :  
khal

### PR DESCRIPTION
**Pull request by nim65s**

### CODE REVIEW

**Comment by geier** [comment]
I'd prefer to retrieve the appropriate length, who knows if 5 is enough for all locales?

**Comment by geier** [comment]
Does anyone know if there is a better way than `max([len(calendar.month_abbr[i]) for i in range(1, 13)])`?

**Comment by geier** [comment]
Also, why is that *really* slow?

**Comment by nim65s** [comment]
hum, I did not found it really slow

**Comment by geier** [comment]
I guess it depends on what you call slow:

```python
In [1]: import calendar

In [2]: %timeit max([len(calendar.month_abbr[i]) for i in range(1, 13)])
10000 loops, best of 3: 45.5 µs per loop

In [3]: tt = [''] + [calendar.month_abbr[i] for i in range(1, 13)]

In [4]: %timeit max([len(tt[i]) for i in range(1, 13)])
1000000 loops, best of 3: 1.88 µs per loop
```

I'm mostly wondering where this factor of 20 versus a list lookup comes from.

**Comment by nim65s** [comment]
```python
In [5]: %timeit [calendar.month_abbr[i] for i in range(1, 13)]
35.2 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by nim65s** [comment]
Yes, `calendar.month_abbr[1]` is almost 3μs, so times 12…

**Comment by geier** [comment]
Thanks! (I bug reports with accompanied fixes are really my favorite kind of bug reports)

**Pull request merged**
