### PR TITLE
Update light theme

### PR DESCRIPTION
**Pull request by augustus-rex**
This pull request is related to pull request #614. This request modifies the light theme instead of creating a new solarized_light theme.

### CODE REVIEW

**Comment by geier** [comment]
Thanks! I merged #618 together with #616 in f3a3a0e.

**Comment by geier** [comment]
@augustus-rex if you have any ideas on how to improve the coloring of ikhal, please say so. Even if something cannot be styled right now, we can easily change that.

**Comment by augustus-rex** [comment]
Horay, my first merged commit! It's a grand day ^^. And I have no idea for further improvements. With these changes, I find the coloring to be working just fine.

**Comment by geier** [comment]
Congratulations! I remember that day myself (I thought someone should
give me a medal).

Quoting augustus-rex (2017-03-28 19:40:39)

**Comment by augustus-rex** [comment]
Yup, still waiting for that medal!

**Pull request closed without merging**
