### PR TITLE
ikhal : Put '' in alarm desc. if it's NoneType, fix #971

### LINKED ISSUE #971: Alarms with without description cause crash ikhal
Events that have alarms without the `DESCRIPTION` attribute crash ikhal

This ics triggers that behavior
```
BEGIN:VCALENDAR
PRODID:ics.py - http://git.io/lLljaA
VERSION:2.0
BEGIN:VEVENT
DURATION:PT1M
LOCATION:redacted
DTSTART:20201217T050000Z
SUMMARY:redacted
UID:02ab966f90e6c3e11da0d612638b90de9a678d030d44d2be0dc11b20b3d6b9d8
CATEGORIES:
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT10H
END:VALARM
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
```

### PR DESCRIPTION
**Pull request by ephase**
really simple Fix for issue #971

### CODE REVIEW

**Comment by d7415** [comment]
I haven't tested it in action, but it looks good. Could you amend your commit message to the right number? Or I guess a squash merge might let do that during merge. I forget.

**Comment by ephase** [comment]
Ho sorry, I inverted two numbers

**Comment by d7415** [comment]
Easily done, just keeps the history clearer this way :)

**Review by d7415 — APPROVED** [review]

**Comment by d7415** [comment]
Merged in 7f288f5

**Pull request closed without merging**
