### PR TITLE
Add new permutations for testing print_ics and condense into re. Fixes #1065

### LINKED ISSUE #1065: `test_print_ics_command` test fails with click>=8.0
`test_print_ics_command` from `tests/cli_test.py` seems to fail if the `click` dependency is at version 8.0.1. This happens both with master and version 0.10.3 of khal itself. It seems to be related to click changing its output format in this situation. 

```
runner = <tests.cli_test.CustomCliRunner object at 0x7f02364d74f0>

    def test_print_ics_command(runner):
        runner = runner()
        # Input is empty and loading from stdin
        result = runner.invoke(main_khal, ['printics', '-'])
        assert result.exception
    
        # Non existing file
        result = runner.invoke(main_khal, ['printics', 'nonexisting_file'])
        assert result.exception
>       assert (
            'Error: Invalid value for "ics": Could not open file: ' in result.output or
            'Error: Invalid value for "[ICS]": Could not open file:'
            in result.output or
            'Error: Invalid value for \'ics\': Could not open file: ' in result.output or
            'Error: Invalid value for \'[ICS]\': Could not open file:'
            in result.output)
E       assert ('Error: Invalid value for "ics": Could not open file: ' in "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" or 'Error: Invalid value for "[ICS]": Could not open file:' in "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" or "Error: Invalid value for 'ics': Could not open file: " in "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" or "Error: Invalid value for '[ICS]': Could not open file:" in "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n")
E        +  where "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" = <Result SystemExit(2)>.output
E        +  and   "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" = <Result SystemExit(2)>.output
E        +  and   "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" = <Result SystemExit(2)>.output
E        +  and   "Usage: cli printics [OPTIONS] [ICS]\nTry 'cli printics --help' for help.\n\nError: Invalid value for '[ICS]': 'nonexisting_file': No such file or directory\n" = <Result SystemExit(2)>.output

tests/cli_test.py:673: AssertionError
```

This test passes if I install click at 7.1.2.

### PR DESCRIPTION
**Pull request by d7415**
This adds the permutations from #1065 into the valid responses. 8 options seemed excessive, so I've condensed it into a regular expression. Happy to hear any objections to that.

### CODE REVIEW

**Comment by d7415** [comment]
Py3.6 tests fail because vdirsyncer has dropped 3.6 support. We can either do the same, tell that test to fail, or pin an old version for that test.
mypy have completely changed how they handle libraries. Yay.

**Comment by DeeUnderscore** [comment]
Solves #1065 for me, thanks

**Comment by d7415** [comment]
Fixed mypy.

**Comment by d7415** [comment]
I didn't want to batch too much into one PR, but as we've run out of OSS credits on Travis again I've included some tweaks to run more tests on GItHub Actions.

**Comment by d7415** [comment]
I'm going to hold off on this until we fix CI, then I'll rebase/clean it.

**Pull request closed without merging**
