### PR TITLE
Use the system locale's formats as a default

### PR DESCRIPTION
**Pull request by hobarrera**
By default, use the system locale for date and time formats. This should (generally) provide defaults with which the user is more familiar, without affecting reconfigurability at all.

This _should not_ change anything for users that have specified a format, and does not limit and configuration options at all.

### CODE REVIEW

**Comment by hobarrera** [comment]
Bump?

If this sounds like a bad idea, a single config flag like `user_system_locale` might cover that activates this behaviour might be a good option too.

**Comment by geier** [comment]
please add an entry to the CHANGELOG

**Comment by hobarrera** [comment]
Oops, I'd pushed this to the wrong branch.

**Comment by hobarrera** [comment]
Bump!

**Comment by geier** [comment]
I haven't forgotten about this and will merge this eventually. I am still hesitant to merge this at the moment, as it it breaks the current defaults. Same goes for #585.

**Comment by geier** [comment]
this is blocked by #651

**Pull request closed without merging**
