### PR TITLE
Python 3.6 support

### PR DESCRIPTION
**Pull request by hobarrera**
Nothing fancy, just run tests with py36 to make sure we don't break anything.

### CODE REVIEW

**Comment by hobarrera** [comment]
Sorry, I kind I fired this assuming it *would* build, since I didn't see any breaking changes.

Looks like datetime comparison is messed up. I'll try and determine if it's a python 3.6 issue or not.

**Comment by geier** [comment]
I would have expected it to build as well...

**Comment by hobarrera** [comment]
Downstream packages are failing to run tests now [with 0.9.0], returning the same error. :(

**Comment by geier** [comment]
@hobarrera do you want to rebase to master? Feel free to merge yourself.

**Comment by geier** [comment]
merged a10f95833ef1f303456e8398a3143e242866ccd9

**Pull request closed without merging**
