### PR TITLE
add alarm symbol for events with at least one alarm

### LINKED ISSUE #674: Show alarm symbol (⏰) in khal
I like that `khal calendar`/`ikhal` shows recurring events with a `⟳` symbol and propose do have a symbol that marks events with any alarm set with a `⏰` (or some similar) symbol.

### PR DESCRIPTION
**Pull request by sdx23**
fixes #674

Would be glad about some feedback on how you want this to be tested (if at all). Note that some tests are failing, but those are the same that have been failing before as well (platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0).

Edit: note that I chose the notes symbol because that was supported by my default font (Bitstream vera sans mono) in contrast to the other suggestions. They seem to be newer and possibly less supported.

### CODE REVIEW

**Review by WhyNotHugo — COMMENTED** [review]
Does `⏰` not work for you?

PR looks good to me. I won't hold back based on the default icon decision, but I do think it should be customizable.

**Comment by sdx23** [comment]
No, sadly ⏰ doesn't work for me. However, you may well change the icon as you wish.

**Review by d7415 — COMMENTED** [review]
My main reservation was also the symbol used. FWIW as part of my testing I have pushed a commit with the ⏰ symbol (and deconflicted with latest master) to the `sdx23_pr1043` branch.

**Review by WhyNotHugo — APPROVED** [review]

**Comment by WhyNotHugo** [comment]
Merged. Thanks!

**Comment by d7415** [comment]
> it's configurable

Is it..?

**Comment by sdx23** [comment]
Sorry for not following up on this one. After the `sdx23_pr1043` branch was introduced I'd have expected that one to be merged, not the original PR.

> Is it..?

Yes and no. It is configurable **whether** a symbol is shown but not **which**.

**Comment by WhyNotHugo** [comment]
Oh, my bad. I must have mixed up the branch on this PR and `sdx23_pr1043` (I think I read one, but merged the other).

Do you want to open a PR with the additional changes in that one?

**Comment by d7415** [comment]
I think the only main difference was the symbol. It looks like it's also reverted one of the formatting fixes though. I'll go fix that part now. Symbol is up to you - I prefer the clock (usage also says `An alarm symbol (alarm clock)`) but it's not a big deal either way.

**Comment by WhyNotHugo** [comment]
I'd rather have the icon be configurable TBH. If you want to open a PR changing it though, I'm not opposed.

Again, I [mis]merged since I mixed up the branches. :sweat:

**Comment by sdx23** [comment]
There you go: https://github.com/sdx23/khal/commit/6b721df950db7f068c9fed085ea956833850a884

I have no glue how to add that commit to this pr or whether that's possible at all.

Personally I'm in favor of just changing it to '\N{Alarm clock}'. The other symbols are not configurable as well.

**Pull request merged**
