### PR TITLE
Install type stubs and dependencies for mypy

### PR DESCRIPTION
**Pull request by WhyNotHugo**
mypy no longer ships type stubs and they must now be installed
separately.

Configure tox to install these for the `mypy` environment, as well as
regular dependencies (since many of these include typing hints
themselves).

I've moved `ignore_missing_imports` to a mypy-specific section, so when
mypy is run via other tools (e.g.: code editors) this settings is
applied too.

### CODE REVIEW

**Comment by d7415** [comment]
Alternative would be `mypy --install-types --non-interactive --ignore-missing-imports khal`. Probably less correct, but it means we're less likely to miss a dependency later on. I added it to #1066 (which does need splitting up) (https://github.com/pimutils/khal/pull/1066/commits/e68c050f71c877e55efb976f12d5c5eadf600c59)

**Comment by WhyNotHugo** [comment]
> Note that using the --install-types is problematic. Mutating the pre-commit environment at runtime breaks cache and will break parallel builds.

https://github.com/pre-commit/mirrors-mypy

**Comment by WhyNotHugo** [comment]
(ignore that last message, mixup)

**Comment by WhyNotHugo** [comment]
I think `--install-types --non-interactive` is better than what I'm doing here.

`--ignore-missing-imports`, however, should be specified in `setup.cfg` or `tox.ini`, so that other tools can pick that value up (e.g.: mypy when run via `nvim`).

**Comment by d7415** [comment]
> `--ignore-missing-imports`, however, should be specified in `setup.cfg` or `tox.ini`, so that other tools can pick that value up (e.g.: mypy when run via `nvim`).

That makes sense. I feel like I've seen that elsewhere.

**Comment by WhyNotHugo** [comment]
`todoman` and `vdirsyncer` follow that pattern, and it's pretty common in general.

**Review by d7415 — APPROVED** [review]
Makes sense to me.

**Pull request merged**
